-- AlterTable
ALTER TABLE "StoreUsage" ADD COLUMN     "aiImageUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "aiSeoUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "freeQuotaLimit" INTEGER NOT NULL DEFAULT 100;
