type AdminGraphql = {
  graphql: (
    query: string,
    options?: { variables?: Record<string, unknown> },
  ) => Promise<Response>;
};

export type SitemapItem = {
  title: string;
  url: string;
  kind: "product" | "collection" | "page";
};

async function shopPrimaryBase(admin: AdminGraphql): Promise<string> {
  const response = await admin.graphql(
    `#graphql
      query SeoSitemapShopDomain {
        shop {
          primaryDomain { url }
          myshopifyDomain
        }
      }`,
  );
  const json = (await response.json()) as {
    data?: {
      shop?: {
        primaryDomain?: { url?: string | null } | null;
        myshopifyDomain?: string | null;
      };
    };
  };
  return (
    json.data?.shop?.primaryDomain?.url?.replace(/\/$/, "") ||
    `https://${json.data?.shop?.myshopifyDomain || "shop.myshopify.com"}`
  );
}

export async function fetchSitemapItems(
  admin: AdminGraphql,
): Promise<{ base: string; items: SitemapItem[]; shopName: string }> {
  const base = await shopPrimaryBase(admin);

  const response = await admin.graphql(
    `#graphql
      query SeoSitemapCatalog {
        shop { name }
        products(first: 100, query: "status:active") {
          nodes {
            title
            handle
            onlineStoreUrl
          }
        }
        collections(first: 50) {
          nodes {
            title
            handle
          }
        }
        pages(first: 50) {
          nodes {
            title
            handle
          }
        }
      }`,
  );

  const json = (await response.json()) as {
    data?: {
      shop?: { name?: string };
      products?: {
        nodes?: Array<{
          title?: string;
          handle?: string;
          onlineStoreUrl?: string | null;
        }>;
      };
      collections?: { nodes?: Array<{ title?: string; handle?: string }> };
      pages?: { nodes?: Array<{ title?: string; handle?: string }> };
    };
    errors?: { message?: string }[];
  };

  if (json.errors?.length) {
    throw new Error(json.errors[0]?.message || "Sitemap query failed.");
  }

  const items: SitemapItem[] = [];

  for (const p of json.data?.products?.nodes ?? []) {
    if (!p.handle) continue;
    items.push({
      title: p.title || p.handle,
      url: p.onlineStoreUrl || `${base}/products/${p.handle}`,
      kind: "product",
    });
  }

  for (const c of json.data?.collections?.nodes ?? []) {
    if (!c.handle) continue;
    items.push({
      title: c.title || c.handle,
      url: `${base}/collections/${c.handle}`,
      kind: "collection",
    });
  }

  for (const page of json.data?.pages?.nodes ?? []) {
    if (!page.handle) continue;
    items.push({
      title: page.title || page.handle,
      url: `${base}/pages/${page.handle}`,
      kind: "page",
    });
  }

  return {
    base,
    items,
    shopName: json.data?.shop?.name || "Store",
  };
}

export function renderHtmlSitemap(args: {
  shopName: string;
  items: SitemapItem[];
  base: string;
}): string {
  const byKind = {
    product: args.items.filter((i) => i.kind === "product"),
    collection: args.items.filter((i) => i.kind === "collection"),
    page: args.items.filter((i) => i.kind === "page"),
  };

  const section = (title: string, rows: SitemapItem[]) => {
    if (rows.length === 0) return "";
    const lis = rows
      .map(
        (r) =>
          `<li><a href="${escapeHtml(r.url)}">${escapeHtml(r.title)}</a></li>`,
      )
      .join("\n");
    return `<h2>${escapeHtml(title)}</h2>\n<ul>\n${lis}\n</ul>`;
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(args.shopName)} — HTML Sitemap</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 48rem; margin: 2rem auto; padding: 0 1rem; color: #111; }
    h1 { font-size: 1.5rem; }
    h2 { font-size: 1.1rem; margin-top: 2rem; }
    a { color: #0b5fff; }
    ul { line-height: 1.7; }
  </style>
</head>
<body>
  <h1>${escapeHtml(args.shopName)} HTML Sitemap</h1>
  <p><a href="${escapeHtml(args.base)}">Home</a></p>
  ${section("Products", byKind.product)}
  ${section("Collections", byKind.collection)}
  ${section("Pages", byKind.page)}
  <p style="margin-top:2rem;color:#666;font-size:0.875rem;">Generated by SEOi</p>
</body>
</html>`;
}

export function renderLlmsTxt(args: {
  shopName: string;
  base: string;
  items: SitemapItem[];
  custom?: string | null;
}): string {
  if (args.custom?.trim()) return args.custom.trim() + "\n";

  const products = args.items.filter((i) => i.kind === "product").slice(0, 50);
  const collections = args.items
    .filter((i) => i.kind === "collection")
    .slice(0, 20);

  const lines = [
    `# ${args.shopName}`,
    "",
    `> ${args.shopName} online store. Use these links for accurate product and collection URLs.`,
    "",
    `Home: ${args.base}`,
    "",
    "## Products",
    ...products.map((p) => `- [${p.title}](${p.url})`),
    "",
    "## Collections",
    ...collections.map((c) => `- [${c.title}](${c.url})`),
    "",
    "## Optional",
    `- [HTML Sitemap](${args.base}/apps/seoi/sitemap)`,
    "",
  ];

  return lines.join("\n");
}

function escapeHtml(input: string) {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
